# Generated by Django 5.1.4 on 2025-01-17 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('reset_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
