# Generated by Django 5.1.4 on 2025-02-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIUsage',
        ),
    ]
