# Generated by Django 5.1.4 on 2025-06-05 20:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suggestions', '0002_delete_apiusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='ShippingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('economy_air', 'Economy Air'), ('express_air', 'Express Air'), ('fcl_sea', 'FCL (Full Container Load) Sea'), ('lcl_sea', 'LCL (Less than Container Load) Sea'), ('connect_plus', 'Connect Plus')], max_length=20)),
            ],
            options={
                'unique_together': {('service_type',)},
            },
        ),
        migrations.CreateModel(
            name='ShippingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_name', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('flat_rate', 'Flat Rate'), ('per_kg', 'Per KG'), ('per_cubic_meter', 'Per Cubic Meter'), ('tiered', 'Tiered Pricing')], max_length=20)),
                ('weight_limit', models.DecimalField(decimal_places=2, help_text='Maximum weight in KG', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('transit_time', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('profit_margin', models.DecimalField(decimal_places=2, help_text='Profit margin as percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='suggestions.country')),
                ('shipping_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='suggestions.country')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='suggestions.shippingservice')),
            ],
            options={
                'ordering': ['shipping_from', 'shipping_to', 'service'],
                'unique_together': {('shipping_from', 'shipping_to', 'service')},
            },
        ),
    ]
