# Generated by Django 5.1.4 on 2025-06-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingroute',
            name='condition',
        ),
    ]
