# Generated by Django 5.1.4 on 2025-07-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0004_remove_shippingroute_condition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingroute',
            unique_together={('shipping_from', 'shipping_to', 'service', 'min_weight')},
        ),
    ]
