# Generated by Django 5.1.4 on 2025-04-28 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('sourcing', 'Sourcing'), ('shipment', 'Shipment'), ('warehouse', 'Warehouse')], max_length=20)),
                ('notification_type', models.CharField(choices=[('sourcing_status', 'Sourcing Status Update'), ('quotation_created', 'Quotation Created'), ('quotation_updated', 'Quotation Updated'), ('sourcing_shipping_status', 'Sourcing Shipping Status Update'), ('shipment_created', 'Shipment Created'), ('shipment_status', 'Shipment Status Update'), ('shipment_tracking', 'Tracking Number Added'), ('shipment_payment', 'Shipment Payment Status'), ('inbound_status', 'Inbound Shipment Status'), ('inbound_created', 'Inbound Shipment Created'), ('outbound_created', 'Outbound Shipment Created'), ('outbound_status', 'Outbound Shipment Status'), ('inventory_update', 'Inventory Update')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('object_id', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_url', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_543da6_idx'), models.Index(fields=['app_name', 'user'], name='notificatio_app_nam_29328d_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_743343_idx')],
            },
        ),
    ]
