# Generated by Django 5.1.4 on 2025-02-18 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_warehouse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inbound_shipments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.inboundshipment'),
        ),
    ]
