# Generated by Django 5.1.4 on 2025-03-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_variation_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='options',
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='warehouse.product'),
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Option name (e.g., Red, Blue, Small)', max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='warehouse.variation')),
            ],
        ),
    ]
