# Generated by Django 5.1.4 on 2025-03-07 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_variation_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.JSONField(help_text="Address as {'label': str, 'value': str}")),
                ('tracking_number', models.CharField(max_length=255, unique=True)),
                ('shipment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_shipments', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_shipments', to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('outbound_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.outboundshipment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_items', to='warehouse.product')),
                ('variation_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbound_items', to='warehouse.variationoption')),
            ],
        ),
    ]
