# Generated by Django 5.1.4 on 2025-03-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_inboundshipment_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundshipment',
            name='pending_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='outboundshipment',
            name='pending_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
