# Generated by Django 5.1.4 on 2025-03-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_inboundshipment_pending_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundshipment',
            name='shipment_number',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
