# Generated by Django 5.1.4 on 2025-03-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_outboundshipment_shipment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundshipment',
            name='shipment_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inboundshipment',
            name='tracking_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundshipment',
            name='shipment_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='outboundshipment',
            name='tracking_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100),
        ),
    ]
