# Generated by Django 5.1.4 on 2025-01-22 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type', models.CharField(blank=True, choices=[('20FR', "20' FLAT RACK CNTR(S)"), ('20OT', "20' OPEN TOP CNTR(S)"), ('20PL', "20' PLATFORM(S)"), ('20RE', "20' REEFER(S)"), ('40HR', "40' HIGH CUBE REEFER(S)"), ('40FR', "40' FLAT RACK CNTR(S)"), ('40RE', "40' REEFER(S)"), ('40OT', "40' OPEN TOP CNTR(S)"), ('40PL', "40' PLATFORM(S)"), ('40ST', "40' STANDARD CNTR(S)"), ('40HC', "40' HIGH CUBE CNTR(S)"), ('20ST', "20' STANDARD CNTR(S)")], max_length=10, null=True)),
                ('package_type', models.CharField(blank=True, choices=[('boxes', 'Boxes'), ('crates', 'Crates'), ('pallets', 'Pallets'), ('wooden_box', 'Wooden Box')], max_length=10, null=True)),
                ('length', models.FloatField(help_text='Length in cm')),
                ('width', models.FloatField(help_text='Width in cm')),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_per_unit', models.FloatField(help_text='Weight per unit in kg')),
                ('hs_code', models.CharField(help_text='Harmonized System Code for customs classification', max_length=10)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shipments.container')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20)),
                ('international_shipping_type', models.CharField(blank=True, choices=[('economy_air', 'Economy Air'), ('express_air', 'Express Air'), ('fcl_sea', 'FCL (Full Container Load) Sea'), ('lcl_sea', 'LCL (Less than Container Load) Sea')], max_length=20, null=True)),
                ('incoterm', models.CharField(choices=[('FOB', 'FOB - Free On Board'), ('CPT', 'CPT - Carriage Paid To'), ('CIF', 'CIF - Cost, Insurance and Freight'), ('DAP', 'DAP - Delivered At Place'), ('DDP', 'DDP - Delivered Duty Paid')], max_length=10)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('insure_shipment', models.BooleanField(default=False)),
                ('insurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('pickup_date', models.DateField()),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('receiver_vat_no', models.CharField(blank=True, help_text="Receiver's VAT number", max_length=50, null=True)),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='shipments.shipment'),
        ),
    ]
