# Generated by Django 5.1.4 on 2025-01-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='receiver_email',
            new_name='sender_email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_per_unit',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='receiver_phone',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='receiver_vat_no',
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_tax_vat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_type',
            field=models.CharField(blank=True, choices=[('20ST', "20' DRY STANDARD "), ('40ST', "40' DRY STANDARD ")], max_length=10, null=True),
        ),
    ]
