# Generated by Django 5.1.4 on 2025-01-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_rename_receiver_email_shipment_sender_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
