# Generated by Django 5.1.4 on 2025-02-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_remove_product_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='delivery_address',
            field=models.JSONField(help_text="Stores the delivery address as {'label': str, 'value': str}"),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pickup_address',
            field=models.JSONField(help_text="Stores the pickup address as {'label': str, 'value': str}"),
        ),
    ]
