# Generated by Django 5.1.4 on 2025-03-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_product_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='value',
            new_name='product_value',
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
