# Generated by Django 5.1.4 on 2025-03-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_rename_value_product_product_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='total_weight',
            field=models.FloatField(blank=True, default=0.0, help_text='Sum of all container weights * quantity in kg', null=True),
        ),
    ]
