# Generated by Django 5.1.4 on 2025-04-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_shipment_total_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_dangerous_goods',
            field=models.BooleanField(default=False, help_text='Indicates if the shipment contains dangerous goods like batteries'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_one_percent_insured',
            field=models.BooleanField(default=False, help_text='If true, 1% of order value is used as insurance'),
        ),
    ]
