# Generated by Django 5.1.4 on 2025-05-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_shipment_is_dangerous_goods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='international_shipping_type',
            field=models.CharField(blank=True, choices=[('economy_air', 'Economy Air'), ('express_air', 'Express Air'), ('fcl_sea', 'FCL (Full Container Load) Sea'), ('lcl_sea', 'LCL (Less than Container Load) Sea'), ('connect_plus', 'connect_plus')], max_length=20, null=True),
        ),
    ]
