# Generated by Django 5.1.4 on 2025-07-14 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_alter_shipment_international_shipping_type'),
        ('suggestions', '0005_alter_shippingroute_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='base_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base cost from the shipping route', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_country',
            field=models.ForeignKey(blank=True, help_text='Destination country for easier filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_shipments', to='suggestions.country'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_country',
            field=models.ForeignKey(blank=True, help_text='Origin country for easier filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_shipments', to='suggestions.country'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='profit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual profit amount (delivery_price - base_cost)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='profit_margin_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Profit margin percentage applied', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_route',
            field=models.ForeignKey(blank=True, help_text='The shipping route used for this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='suggestions.shippingroute'),
        ),
        migrations.AlterField(
            model_name='container',
            name='container_type',
            field=models.CharField(blank=True, choices=[('20ST', "20' DRY STANDARD"), ('40ST', "40' DRY STANDARD")], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='international_shipping_type',
            field=models.CharField(blank=True, choices=[('economy_air', 'Economy Air'), ('express_air', 'Express Air'), ('fcl_sea', 'FCL (Full Container Load) Sea'), ('lcl_sea', 'LCL (Less than Container Load) Sea'), ('connect_plus', 'Connect Plus')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['user', 'created_at'], name='shipments_s_user_id_a5db8b_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['origin_country', 'created_at'], name='shipments_s_origin__1da1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['payment_status', 'created_at'], name='shipments_s_payment_38e569_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_s_status_536511_idx'),
        ),
    ]
