# Generated by Django 5.1.4 on 2025-01-18 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity_needed', models.PositiveIntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='sourcing_requests/')),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Under Review'), ('quotation_sent', 'Quotation Sent'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('live_tracking_url', models.URLField(blank=True, null=True)),
                ('sourcing_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='sourcing.sourcingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sourcing_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='sourcing.sourcingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('sourcing_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='sourcing.sourcingrequest')),
            ],
        ),
    ]
