# Generated by Django 5.1.4 on 2025-02-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcingrequest',
            name='images',
            field=models.ImageField(upload_to='sourcing_requests/'),
        ),
    ]
