# Generated by Django 5.1.4 on 2025-02-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0002_alter_sourcingrequest_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcingrequest',
            name='address',
            field=models.JSONField(help_text="Address as {'label': str, 'value': str}"),
        ),
    ]
