# Generated by Django 5.1.4 on 2025-04-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0003_alter_sourcingrequest_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingrequest',
            name='target_price',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
