# Generated by Django 5.1.4 on 2025-04-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0005_remove_shipping_live_tracking_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='quotation_price',
            new_name='air_shipment_cost',
        ),
        migrations.AddField(
            model_name='quotation',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='truck_shipment_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
