# Generated by Django 5.1.4 on 2025-04-26 15:24

import sourcing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0006_rename_quotation_price_quotation_air_shipment_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingrequest',
            name='reference_number',
            field=models.CharField(default=sourcing.models.generate_reference_number, editable=False, max_length=10, unique=True),
        ),
    ]
