# Generated by Django 5.1.4 on 2025-04-26 15:25

import sourcing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0007_sourcingrequest_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcingrequest',
            name='reference_number',
            field=models.CharField(blank=True, default=sourcing.models.generate_reference_number, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
