# Generated by Django 5.1.4 on 2025-04-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0008_alter_sourcingrequest_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcingrequest',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
