# Generated by Django 5.1.4 on 2025-04-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0009_alter_sourcingrequest_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sea_shipment_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
