# Generated by Django 5.1.4 on 2025-05-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0010_quotation_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('review', 'Under Review'), ('quotation_sent', 'Quotation Sent'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('quotation_rejected', 'Quotation Rejected')], default='pending', max_length=50),
        ),
    ]
